# Generated by Django 3.1 on 2020-08-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Records_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(blank=True, max_length=200)),
                ('trading_date', models.CharField(max_length=200)),
                ('closing_price', models.CharField(max_length=200)),
                ('price_difference', models.CharField(blank=True, max_length=100)),
                ('lower_price_circuit', models.CharField(blank=True, max_length=200)),
                ('upper_price_circuit', models.CharField(blank=True, max_length=200)),
                ('no_of_days_since_last_circuit', models.CharField(blank=True, max_length=200)),
                ('up_or_down_circuit_indicator', models.CharField(blank=True, max_length=200)),
                ('no_of_rises', models.IntegerField(blank=True, default=0)),
                ('no_of_falls', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Historical_stock_prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(blank=True, max_length=200)),
                ('trading_date', models.CharField(max_length=200)),
                ('closing_price', models.CharField(max_length=200)),
                ('price_difference', models.CharField(blank=True, max_length=100)),
                ('lower_price_circuit', models.CharField(blank=True, max_length=200)),
                ('upper_price_circuit', models.CharField(blank=True, max_length=200)),
                ('no_of_days_since_last_circuit', models.CharField(blank=True, max_length=200)),
                ('up_or_down_circuit_indicator', models.CharField(blank=True, max_length=200)),
                ('no_of_rises', models.IntegerField(blank=True, default=0)),
                ('no_of_falls', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True, max_length=100)),
                ('Action', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recently_Updated_Records',
            fields=[
                ('stock_name', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('trading_date', models.CharField(blank=True, max_length=100)),
                ('closing_price', models.CharField(blank=True, max_length=200)),
                ('price_difference', models.CharField(blank=True, max_length=100)),
                ('upper_price_circuit', models.CharField(blank=True, max_length=200)),
                ('lower_price_circuit', models.CharField(blank=True, max_length=200)),
                ('no_of_days_since_last_circuit', models.CharField(blank=True, max_length=200)),
                ('up_or_down_circuit_indicator', models.CharField(blank=True, max_length=200)),
                ('no_of_rises', models.IntegerField(blank=True, default=0)),
                ('no_of_falls', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
